/** South Africa ranking boosts for nearby destination suggestions. */

export const saBoost: Record<string, number> = {
  "university of johannesburg": 10,
  uj: 10,
  wits: 10,
  "university of the witwatersrand": 10,
  "fort hare": 10,
  unisa: 8,
  uct: 10,
  ukzn: 8,
  tuks: 8,
  "sandton city": 10,
  "mall of africa": 10,
  "maponya mall": 9,
  menlyn: 9,
  gateway: 9,
  "v&a waterfront": 10,
  "park station": 9,
  gautrain: 9,
  "taxi rank": 8,
  "bree street": 9,
  shoprite: 7,
  checkers: 6,
  spar: 6,
  picknpay: 6,
  "pick n pay": 6,
  shell: 7,
  bp: 7,
  engen: 7,
  total: 7,
  baragwanath: 8,
  soweto: 6,
  sandton: 6,
};

export const saCategoryBoost: Record<string, number> = {
  restaurant: 3,
  fast_food: 4,
  shop: 4,
  grocery: 5,
  mall: 6,
  university: 8,
  school: 4,
  hospital: 5,
  fuel: 5,
  bus_station: 4,
  taxi: 6,
};
